basePath: /
host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: author：@ouzhsh
    url: http://www.swagger.io/support
  description: Go Web 开发通用脚手架模板
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: web_app
  version: 0.0.1
paths: {}
swagger: "2.0"
